language: node_js
node_js: "9"
services: docker

# before_install: yarn global add greenkeeper-lockfile@1

# before_script: greenkeeper-lockfile-update

# script: bash ./scripts/test-ci

# after_script:
#   - docker-compose -f docker-compose-tests.yml down -v
#   - greenkeeper-lockfile-upload

script: bash ./scripts/deploy.sh
