version: '2.1'

services:

  test:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-watch
    volumes:
      - node_modules:/code/node_modules
      - .:/code
    environment:
      API_HOSTNAME: ${API_HOSTNAME-https://dummy.url}

  tests-unit:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-unit-watch
    volumes:
      - node_modules:/code/node_modules
      - .:/code

  tests-integration:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-integration-watch
    volumes:
      - node_modules:/code/node_modules
      - .:/code
    environment:
      API_HOSTNAME: ${API_HOSTNAME-https://dummy.url}
      SEARCH_API_HOST: ${SEARCH_API_HOST-https://dummy.url}

  test-ci:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-ci
    user: root
    volumes:
      - node_modules:/code/node_modules
    environment:
      API_HOSTNAME: ${API_HOSTNAME-https://dummy.url}
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      SEARCH_API_HOST: ${SEARCH_API_HOST-https://dummy.url}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

volumes:
  node_modules:
