version: '2.1'

services:

  test:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn test-watch
    volumes:
      - node_modules:/code/node_modules
      - .:/code
    environment:
      SEARCH_API_HOST: https://dummy.url

  tests-unit:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn test-unit-watch
    volumes:
      - node_modules:/code/node_modules
      - .:/code

  test-ci:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn test-and-upload-coverage
    user: root
    volumes:
      - node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      SEARCH_API_HOST: https://dummy.url
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

volumes:
  node_modules:
